### ISSUE TITLE
AFL style tracing Question

### ISSUE THREAD

**Issue by y1026** [denandz/fuzzotron#1]
Hello,

I ran AFL using the AFL style tracing.

After compiling AFL, execute AFL style tracing command.

However, the Path does not increase in the log.

and No additional files are created in the testcase folder.

Is this normal?

Thanks.

Log
```
Loaded Paths: 0 Jettisoned: 0
Sent Cases: 80 Paths:0 Jettisoned: 5
```

**Comment by denandz** [comment]
Hi,

Have you set the __AFL_SHM_ID environment variable when launching the target daemon?

**Comment by denandz** [comment]
Hmm, and the target software is compiled with afl-gcc? Without knowing more about the target I'm not sure how much help I can be. I'd say make sure that the target is A) compiled with afl-gcc (or afl-clang-fast or whatevre) and B) that the __AFL_SHM_ID environment variable is set for the daemon process that's to be fuzzed.

**Comment by y1026** [comment]
@denandz 

Hello,

Thank you for your quick reply.

I have used afl-fuzz.

I succeeded in a small source. (https://github.com/kentakozuka/little_httpd)

```
[+] Spawning worker thread 1
[.] Worker 1 alive
[.] Trace enabled
[-] Sent cases: 2 Paths:2 Jettisoned: 0
[.] Loaded Paths: 2 Jettisoned: 0
[.] Deterministic mutations completed, sent: 51 paths: 2
[.] Sent cases: 4547 Paths:4 Jettisoned: 0
```

But, It does not work with solutions that use large sources.

I'll go ahead with some more fuzzing. More than 1 hour.

Thanks.

**Comment by y1026** [comment]
Hello,

I still have failed AFL style tracing. 

But it does not seem to be a problem of fuzzotron. Because it works well in other applications.

And I have a question. 

I found a crash through Fuzzotron.

I used the following command, but it fails to reproduce the problem.

```
for i in $(ls output/*); do echo "firing $i"; ncat <target> <port> < $i; done
```

To solve the problem, Is it best to use tcpdump?

In my opinion, adding the pcap collection option to Fuzzotron would be a great help. 

Thanks.

**Comment by denandz** [comment]
Hey, I'd suggest running a rolling tcpdump while performing the fuzzing. Given that fuzzotron just sends testcases to the target as fast as possible, its often difficult to determine exactly which specific testcase triggered the crash. In some cases, it could be a combination of test cases triggering some kind of vulnerable state within the target. Running a rolling tcpdump and then replaying the packets, as well as gathering address-sanitizer outputs when the crash happens would be the best bet. 

I'm a little apprehensive about adding pcap collection and that sort of thing into fuzzotron, I'd like to keep it as simple as possible. There are a few additional features that I'll be releasing shortly, so i'll consider adding it in at a later stage.

**Comment by y1026** [comment]
@denandz 

Ok.  Thank you for answer.

fuzzotron is very good tool. 👍 

Thanks.

**Comment by daydayup40** [comment]
@y1026 @denandz maybe your large sources are not single-threaded?
