### ISSUE TITLE
where is the testcase

### ISSUE THREAD

**Issue by a1boyband** [denandz/fuzzotron#16]
[root@linux-driver-test fuzzotron]# ./fuzzotron --blab -g http_request -h 127.0.0.1 -p 80 -P tcp -m /var/log/messages -r 'segfault' -o output
[+] Monitoring logfile /var/log/messages
[+] Spawning monitor
[+] Monitor Spawned!
[+] Spawning worker thread 1
[.] Worker 1 alive
[!] ERROR: no testcases loaded
         Location : load_testcases(), generator.c:196

[root@linux-driver-test fuzzotron]# ./fuzzotron --radamsa --directory testcases/ -h 127.0.0.1 -p 80 -P tcp -o output
[!] ERROR: Could not open testcases/

         Location : main(), fuzzotron.c:89

[root@linux-driver-test fuzzotron]#

**Comment by a1boyband** [comment]
> generated testcases are stored in `/dev/shm/fuzzotron/` while it's running. Blab is picky about grammar location, try specifying the complete path to the grammar. Something like:
> 
> ```
> ./fuzzotron --blab -g /usr/share/blab/html.blab -h 127.0.0.1 -p 80 -P tcp -m /var/log/messages -r 'segfault' -o output
> ```
> 
> I'll update the readme when I get a moment with a better blab example and details on testcase generation

ok,thanks

**Comment by denandz** [comment]
closed by d30e03299f41b7bb4eee3e26d53cf3635c213e1c
