### ISSUE TITLE
README is missing some details

### ISSUE THREAD

**Issue by amlamarra** [denandz/fuzzotron#7]
Hi, I'm just starting to use Fuzzotron but there's a few things in the README that could use clarification and/or correction:

1. The README does not specify what kind of format the files in the "testcases" directory should be or how to get them. I think I know, but I'd like to be sure.
2. What would an "auxiliary check script" look like? Do you have any examples?
3. The sample command for fuzzing DHCP on a router shows one argument as `-P UDP`, but the program requires the protocol to be lower-case, so I had to specify `-P udp`.
4. That same DHCP example does not specify an output directory (`-o output`), which I believe it requires.

**Comment by denandz** [comment]
Thanks for the details. This all sounds like easy README fixes, please send a pull request

**Comment by amlamarra** [comment]
Sure, when I get a chance I'll do that.

**Comment by denandz** [comment]
closed by d30e03299f41b7bb4eee3e26d53cf3635c213e1c
